type subject = {
  element: string[];
  project_id: number;
}

interface WordListType {
  [key:string] : subject;
}

export const WordList : WordListType ={
  globalBlack:{
    element: [
      "처음",
      "무조건",
      "대충",
      "하여튼",
      "구경",
      "죄송",
      "francinette",
      "난생",
      "블로그",
      "응원",
      "화이팅",
      "감탄",
      "그냥",
      "지각",
    ],
    project_id: 0,
  },
  globalWhite:{
    element: [
      "릭",
      "논의",
      "토론",
      "sanitizer",
      "leak",
      "에러",
      "고민",
      "논문",
      "벤치",
      "만족",
      "충족",
      "조건",
      "컨벤션",
      "flag",
      "재사용",
      "최적화",
      "deprecated",
      "비용",
      "구조",
      "복잡도",
      "relink",
      "리링크",
      "ub",
    ],
    project_id: 1,
  },
  libft:{
    element: ["man", "free", "ub", "undefined", "heap"],
    project_id: 1314,
  },
  gnl:{
    element: ["ul", "MAX", "fd", "limit", "테이블", "table"],
    project_id: 1327,
  },
  born2be:{
    element: ["경로", "diff", "ufw", "ssh", "apt", "sudo", "cron"],
    project_id: 1994,
  },
  printf:{
    element: ["ub", "undefined", "부동", "오토마타", "가변", "형식"],
    project_id: 1316,
  },
  pushswap:{
    element: ["복잡도", "시간", "최적", "트리", "tree"],
    project_id: 1471,
  },
  minitalk:{
    element: ["비트", "유니코드", "unicode", "sig", "시그널"],
    project_id: 2005,
  },
  pipex:{
    element: [
      "dup",
      "리다이렉션",
      "redirection",
      "pid",
      "fork",
      "링크",
      "link",
      "프로세스",
      "고아",
    ],
    project_id: 2004,
  },
  solong:{
    element: ["유효", "minilibx", "탐색", "중복", "분할"],
    project_id: 2009,
  },
  fdf:{
    element: ["minilibx", "내적", "vector", "벡터", "투영"],
    project_id: 2008,
  },
  fractol:{
    element: ["minilibx", "julia", "mandelbrot", "zoom", "좌표"],
    project_id: 1476,
  },
  philo:{
    element: [
      "동기화",
      "교착",
      "기아",
      "데드락",
      "뮤텍스",
      "dead",
      "lock",
      "mutex",
      "세마포어",
      "semaphore",
      "동시성",
      "문맥",
      "race",
      "valgrind",
      "레이스",
    ],
    project_id: 1334,
  },
  minishell:{
    element: [
      "bash",
      "execve",
      "pipex",
      "와일드",
      "wild",
      "스트림",
      "unix",
      "유닉스",
      "리눅스",
      "linux",
      "터미널",
      "terminal",
    ],
    project_id: 1331,
  },

  cpp0:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1338,
  },
  cpp1:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1339,
  },
  cpp2:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1340,
  },
  cpp3:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1341,
  },
  cpp4:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1342,
  },
  cpp5:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1343,
  },
  cpp6:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1344,
  },
  cpp7:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1345,
  },
  cpp8:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 1346,
  },
  cpp9:{
    element: [
      "98",
      "스트림",
      "bit",
      "비트",
      "벡터",
      "vector",
      "fstream",
      "iterator",
      "다형성",
      "추상",
      "인터페이스",
      "template",
      "컨테이너",
    ],
    project_id: 2309,
  },

  netpractice:{
    element: [
      "라우터",
      "router",
      "mask",
      "라우팅",
      "마스크",
      "서브넷",
      "and",
      "osi",
      "프로토콜",
      "protocol",
    ],
    project_id: 2007,
  },
  container:{
    element: [
      "microsoft",
      "마이크로소프트",
      "enable",
      "tree",
      "트리",
      "stl",
      "메타",
      "template",
      "meta",
      "friend",
      "프렌드",
      "sfinae",
    ],
    project_id: 1335,
  },
  inception:{
    element: [
      "vm",
      "virtual",
      "하이퍼",
      "volume",
      "볼륨",
      "이미지",
      "컨테이너",
      "네트워크",
      "pid",
    ],
    project_id: 1983,
  },
  minirt:{
    element: ["vector", "벡터", "뷰", "view", "차원", "opengl", "ray"],
    project_id: 1223,
  },
  cub3d:{
    element: ["long", "so_long", "울펜슈타인", "충돌", "유효", "탐색"],
    project_id: 1326,
  },
  webserv:{
    element: [
      "nginx",
      "엔진엑스",
      "http",
      "queue",
      "curl",
      "telnet",
      "부하",
      "cgi",
      "rfc",
      "poll",
    ],
    project_id: 1338,
  },
  irc:{
    element: [
      "queue",
      "비동기",
      "socket",
      "소켓",
      "rfc",
      "tls",
      "block",
      "프로토콜",
      "protocol",
    ],
    project_id: 1336,
  },
  transcendence:{
    element: ["비동기", "otp", "auth", "socket", "소켓", "엔드", "end"],
    project_id: 1337,
  },
}
