version: '3.5'

services:
  database:
    container_name: ${POSTGRES_DB}
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    networks:
      - 42ondo
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@postgres.postgres'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'

networks:
  42ondo:
